"""Stage 1 — Voice capture.

Audio arrives, is validated, is stored, and becomes a `Recording`. Nothing here
knows where the bytes physically live; that is the storage port's problem.

The validation is the substance of this module. Audio is the one place where a
stranger's bytes enter the system, so every claim the client makes is checked
against the file itself:

* the container is sniffed from magic bytes, not taken from the ``Content-Type``
  header or the filename;
* the object key is generated by us, never derived from a user-supplied filename;
* duration, sample rate and channel count come from ffprobe, never from the
  browser;
* size is capped before anything is written.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from tempfile import TemporaryDirectory

from vtv.adapters.media import ffmpeg
from vtv.contracts.base import IdPrefix, ObjectRef, RetentionClass, new_id
from vtv.contracts.errors import ErrorCode, Status, VTVError
from vtv.contracts.recording import (
    MAX_RECORDING_SECONDS,
    MIN_RECORDING_SECONDS,
    AudioFormat,
    AudioProperties,
    CaptureSource,
    Recording,
)
from vtv.observability.events import EventName, EventSink
from vtv.security.paths import tenant_key

#: Magic-byte signatures we accept. The browser's declared MIME type is a hint;
#: this is the check. ``(offset, signature, format)``.
_SIGNATURES: list[tuple[int, bytes, AudioFormat]] = [
    (0, b"\x1a\x45\xdf\xa3", AudioFormat.WEBM_OPUS),   # Matroska/WebM
    (0, b"OggS", AudioFormat.OGG_OPUS),
    (0, b"RIFF", AudioFormat.WAV_PCM),
    (0, b"fLaC", AudioFormat.FLAC),
    (0, b"ID3", AudioFormat.MP3),
    (0, b"\xff\xfb", AudioFormat.MP3),
    (0, b"\xff\xf3", AudioFormat.MP3),
    (4, b"ftyp", AudioFormat.MP4_AAC),
]

#: Extension used when persisting each format.
_EXTENSIONS: dict[AudioFormat, str] = {
    AudioFormat.WEBM_OPUS: "webm",
    AudioFormat.OGG_OPUS: "ogg",
    AudioFormat.MP4_AAC: "m4a",
    AudioFormat.WAV_PCM: "wav",
    AudioFormat.MP3: "mp3",
    AudioFormat.FLAC: "flac",
}

_CONTENT_TYPES: dict[AudioFormat, str] = {
    AudioFormat.WEBM_OPUS: "audio/webm",
    AudioFormat.OGG_OPUS: "audio/ogg",
    AudioFormat.MP4_AAC: "audio/mp4",
    AudioFormat.WAV_PCM: "audio/wav",
    AudioFormat.MP3: "audio/mpeg",
    AudioFormat.FLAC: "audio/flac",
}

#: A recording that is almost entirely silence is a muted microphone. Catching
#: it here saves the user a wasted minute and saves us a transcription bill.
MAX_SILENCE_RATIO = 0.97


def sniff_format(data: bytes) -> AudioFormat:
    """Identify the container from its magic bytes."""
    for offset, signature, audio_format in _SIGNATURES:
        if data[offset : offset + len(signature)] == signature:
            return audio_format
    raise VTVError(
        "unrecognised audio container",
        code=ErrorCode.AUDIO_UNREADABLE,
        user_message="We could not read that audio file.",
    )


@dataclass
class CaptureService:
    """Turns uploaded bytes into a validated, stored `Recording`."""

    storage: object  # StorageProvider
    events: EventSink
    max_bytes: int = 200 * 1024 * 1024
    max_seconds: float = MAX_RECORDING_SECONDS

    async def capture(
        self,
        *,
        organisation_id: str,
        project_id: str,
        data: bytes,
        source: CaptureSource = CaptureSource.MICROPHONE,
        declared_language: str | None = None,
    ) -> Recording:
        if not data:
            raise VTVError(
                "empty upload",
                code=ErrorCode.AUDIO_UNREADABLE,
                user_message="We did not receive any audio.",
            )
        if len(data) > self.max_bytes:
            raise VTVError(
                f"upload of {len(data)} bytes exceeds the {self.max_bytes} byte limit",
                code=ErrorCode.AUDIO_TOO_LONG,
                user_message="That recording is too large.",
            )

        audio_format = sniff_format(data)
        recording_id = new_id(IdPrefix.RECORDING)
        # Through `tenant_key`, never an f-string. The storage adapter
        # refuses anything outside a tenant namespace, so a raw key here
        # would be an error at write time rather than a silent misplacement.
        key = tenant_key(
            organisation_id,
            "projects",
            project_id,
            "recordings",
            f"{recording_id}.{_EXTENSIONS[audio_format]}",
        )

        ref: ObjectRef = await self.storage.put(  # type: ignore[attr-defined]
            key=key,
            data=data,
            content_type=_CONTENT_TYPES[audio_format],
            retention=RetentionClass.EPHEMERAL,
        )
        self.events.emit(
            EventName.RECORDING_CREATED,
            project_id=project_id,
            data={
                "recording_id": recording_id,
                "format": audio_format.value,
                "bytes": len(data),
                "source": source.value,
            },
        )

        recording = Recording(
            recording_id=recording_id,
            organisation_id=organisation_id,
            project_id=project_id,
            source=source,
            format=audio_format,
            audio=ref,
            declared_language=declared_language,
            status=Status.PROCESSING,
        )
        return await self.probe(recording, data=data)

    async def probe(self, recording: Recording, *, data: bytes | None = None) -> Recording:
        """Measure the audio and complete the recording, or fail it with a reason."""
        payload = data if data is not None else await self.storage.get(recording.audio)  # type: ignore[attr-defined]
        with TemporaryDirectory(prefix="vtv-probe-") as directory:
            scratch = Path(directory) / f"audio.{_EXTENSIONS[recording.format]}"
            scratch.write_bytes(payload)
            try:
                probed = ffmpeg.probe_audio(scratch)
                peak_dbfs, _ = ffmpeg.measure_loudness(scratch)
                regions = ffmpeg.detect_speech_regions(
                    scratch, duration=probed.duration_seconds
                )
            except VTVError as error:
                recording = _failed(recording, error)
                self.events.emit(
                    EventName.STAGE_FAILED,
                    project_id=recording.project_id,
                    data={"stage": "capture", "code": error.info.code.value},
                )
                return recording

        speech_seconds = sum(region.duration for region in regions)
        silence_ratio = max(
            0.0, min(1.0, 1.0 - (speech_seconds / probed.duration_seconds))
        )

        if probed.duration_seconds > self.max_seconds:
            return self._fail(
                recording,
                ErrorCode.AUDIO_TOO_LONG,
                f"recording is {probed.duration_seconds:.0f}s, over the "
                f"{self.max_seconds:.0f}s limit",
                "That recording is longer than we can process.",
            )
        if probed.duration_seconds < MIN_RECORDING_SECONDS:
            return self._fail(
                recording,
                ErrorCode.AUDIO_UNREADABLE,
                "recording is too short to contain anything",
                "That recording was too short.",
            )
        if silence_ratio > MAX_SILENCE_RATIO:
            return self._fail(
                recording,
                ErrorCode.AUDIO_SILENT,
                f"recording is {silence_ratio:.0%} silence",
                "We could not hear anything. Is the microphone muted?",
            )

        recording.properties = AudioProperties(
            duration_seconds=probed.duration_seconds,
            sample_rate_hz=probed.sample_rate_hz,
            channels=probed.channels,
            bit_rate_bps=probed.bit_rate_bps,
            peak_dbfs=peak_dbfs if peak_dbfs is not None and peak_dbfs <= 0 else None,
            silence_ratio=silence_ratio,
        )
        recording.status = Status.READY
        self.events.emit(
            EventName.RECORDING_PROBED,
            project_id=recording.project_id,
            data={
                "recording_id": recording.recording_id,
                "duration_seconds": round(probed.duration_seconds, 3),
                "codec": probed.codec,
                "speech_regions": len(regions),
                "silence_ratio": round(silence_ratio, 3),
            },
        )
        return recording

    def _fail(
        self,
        recording: Recording,
        code: ErrorCode,
        message: str,
        user_message: str,
    ) -> Recording:
        failed = _failed(
            recording, VTVError(message, code=code, user_message=user_message)
        )
        self.events.emit(
            EventName.STAGE_FAILED,
            project_id=recording.project_id,
            data={"stage": "capture", "code": code.value},
        )
        return failed


def _failed(recording: Recording, error: VTVError) -> Recording:
    """Rebuild a recording in the FAILED state, validating the whole object.

    The contract enforces two rules that point at each other: a FAILED
    recording must carry an error, and only a FAILED one may. With
    ``validate_assignment`` on, no order of two assignments satisfies both — so
    the object is revalidated as a whole rather than field by field. Loosening
    either rule would have been the easier fix and the wrong one.
    """
    payload = recording.model_dump()
    payload["status"] = Status.FAILED
    payload["error"] = error.info.model_dump()
    return Recording.model_validate(payload)


__all__ = ["MAX_SILENCE_RATIO", "CaptureService", "sniff_format"]
