"""User media — the assets a person brings, as first-class objects.

Everything else in this system is something the platform produced: a transcript
it heard, a script it split, a visual it chose or drew. This module models the
one category it did not produce, and that difference decides every rule here.

## Why user media is not just another asset

`contracts/asset.py` models material the system *acquired* — licensed, scraped
from a commons, generated by a provider — and its central concern is rights:
nothing is usable until proven usable, and provenance is mandatory because an
enterprise customer will one day ask where a frame came from.

A file the user uploaded has none of those questions. It is theirs. There is no
licence to verify, no attribution to burn into the credits, no provider to
attribute. What it has instead is a stronger claim on the timeline: the system
may re-plan around it, but it may never replace it, and it must still be there
after every re-plan, every regeneration and every style change.

So this is a separate contract with a separate guarantee, rather than an
`AssetSource.USER_UPLOAD` branch inside a model whose validators all exist to
answer questions user media does not raise.

## The five kinds, and why they are not one

An image, a video, an audio file, a logo and an SVG all arrive the same way and
all end up in the same library, but what a user can *do* with each differs
enough that collapsing them would produce an interface full of controls that do
nothing:

* an **image** is cropped and has no duration — it takes the clip's
* a **video** is trimmed and cropped, and its own audio is muted by default
  because the narration owns the sound
* an **audio** file is trimmed, levelled, ducked under the narration and looped
* a **logo** is not a visual at all: it is an overlay placed once per project
  that rides every scene
* an **SVG** is a vector — it scales rather than crops, and its scripts are
  stripped before it is ever rendered

`MediaKind` is therefore load-bearing: `capabilities()` reads from it, and the
API refuses an operation the kind does not support rather than silently
ignoring it.

## Origin

`MediaOrigin` is the vocabulary the whole product uses for "where did this come
from", and it appears in four places — the library card, the script block, the
timeline clip and the inspector. One enum, so those four cannot drift into four
slightly different words for the same fact.
"""

from __future__ import annotations

from enum import Enum

from pydantic import Field, model_validator

from vtv.contracts.base import (
    Id,
    IdPrefix,
    ObjectRef,
    RootDocument,
    Seconds,
    Timestamped,
    VTVModel,
    new_id,
)


class MediaKind(str, Enum):
    """What the file is, and therefore what may be done to it."""

    IMAGE = "image"
    VIDEO = "video"
    AUDIO = "audio"
    #: A brand mark placed once per project as an overlay on every scene.
    #: Never a visual — a logo that filled the frame would be a mistake nobody
    #: asked for.
    LOGO = "logo"
    #: Vector artwork. Scales rather than crops, and is rasterised at render
    #: width with any embedded script stripped first.
    VECTOR = "vector"


class MediaOrigin(str, Enum):
    """Where a piece of material came from. The product's one vocabulary.

    Shown as a badge on the library card, the script block, the timeline clip
    and the inspector. No asset is ever displayed without it — a user who
    cannot tell their own photograph from a model's output cannot make an
    informed decision about either.
    """

    #: The user's own file. No licence question, no attribution, and never
    #: replaced by an automatic process without being asked.
    USER_UPLOAD = "user_upload"
    #: Drawn by the animation engine from the user's own words.
    PROGRAMMATIC = "programmatic"
    #: Third-party. Carries a creator, a licence and a link into the credits.
    LICENSED_SOURCE = "licensed_source"
    #: Model output. Labelled wherever it appears, including in the credits.
    AI_GENERATED = "ai_generated"


class MediaStatus(str, Enum):
    """Where an upload is in its life.

    Four states because the interface has to say something different for each:
    a progress bar, a spinner, a usable thumbnail, and a sentence explaining
    why the file cannot be used.
    """

    UPLOADING = "uploading"
    #: Bytes received; identifying the content and making a thumbnail.
    INGESTING = "ingesting"
    READY = "ready"
    #: Refused by inspection — not a media file, or not one we can decode.
    REFUSED = "refused"


class MediaTrim(VTVModel):
    """The temporal edit on a video or audio asset.

    Stored on the asset rather than on the clip that uses it, because a user who
    trimmed forty seconds down to nine means "this is the nine seconds I care
    about" and expects that to hold everywhere the file is used — not to be
    redone per placement.
    """

    in_seconds: Seconds = Field(default=0.0, ge=0.0)
    #: `None` means "to the end of the file".
    out_seconds: Seconds | None = Field(default=None, ge=0.0)

    #: Audio only. Ends of the clip, in seconds.
    fade_in_seconds: Seconds = Field(default=0.0, ge=0.0, le=10.0)
    fade_out_seconds: Seconds = Field(default=0.0, ge=0.0, le=10.0)

    #: Audio only. Playback level in decibels relative to the source.
    gain_db: float = Field(default=0.0, ge=-60.0, le=12.0)
    #: Audio only. Drop this far further under the narration while it is
    #: speaking. Applied by the renderer, drawn by the editor.
    duck_db: float = Field(default=-10.0, ge=-40.0, le=0.0)
    #: Audio only. Repeat to fill the video rather than stopping.
    loop: bool = False
    #: Video only. A video's own audio is silent unless the user asks for it —
    #: the narration owns the sound, and a clip that arrived with a voice on it
    #: would otherwise talk over the one the user recorded.
    use_source_audio: bool = False

    @model_validator(mode="after")
    def _the_span_advances(self) -> MediaTrim:
        if self.out_seconds is not None and self.out_seconds <= self.in_seconds:
            raise ValueError("a trim must advance: out is not after in")
        return self

    @property
    def duration_seconds(self) -> Seconds | None:
        if self.out_seconds is None:
            return None
        return round(self.out_seconds - self.in_seconds, 3)


class MediaCrop(VTVModel):
    """The spatial edit, in normalised coordinates.

    Normalised rather than in pixels so that the same crop survives a change of
    render resolution. A crop expressed as "start at pixel 640" is a crop that
    silently means something different at 4K.
    """

    x: float = Field(default=0.0, ge=0.0, le=1.0)
    y: float = Field(default=0.0, ge=0.0, le=1.0)
    width: float = Field(default=1.0, gt=0.0, le=1.0)
    height: float = Field(default=1.0, gt=0.0, le=1.0)

    @model_validator(mode="after")
    def _stays_inside_the_frame(self) -> MediaCrop:
        if self.x + self.width > 1.0001 or self.y + self.height > 1.0001:
            raise ValueError("a crop must stay inside the source frame")
        return self

    @property
    def is_whole_frame(self) -> bool:
        return (
            self.x == 0.0
            and self.y == 0.0
            and self.width == 1.0
            and self.height == 1.0
        )


class LogoPlacement(str, Enum):
    TOP_LEFT = "top_left"
    TOP_RIGHT = "top_right"
    BOTTOM_LEFT = "bottom_left"
    BOTTOM_RIGHT = "bottom_right"


class MediaAsset(RootDocument, Timestamped):
    """One file the user brought, and everything known about it."""

    document_name = "media_asset"

    media_asset_id: Id = Field(default_factory=lambda: new_id(IdPrefix.MEDIA_ASSET))
    #: Required and required to be correct: it decides the storage namespace
    #: this file is written to, and `LocalStorageProvider` refuses a key outside
    #: the tenant's own prefix.
    organisation_id: Id
    project_id: Id

    kind: MediaKind
    origin: MediaOrigin = MediaOrigin.USER_UPLOAD
    status: MediaStatus = MediaStatus.UPLOADING

    filename: str = Field(default="", max_length=255)
    content_type: str = Field(default="", max_length=128)
    size_bytes: int = Field(default=0, ge=0)
    #: The bytes. `None` while uploading, and after a refusal.
    object: ObjectRef | None = None

    #: Intrinsic dimensions, where the kind has them.
    width: int | None = Field(default=None, ge=1)
    height: int | None = Field(default=None, ge=1)
    #: Intrinsic length, for video and audio.
    source_duration_seconds: Seconds | None = Field(default=None, ge=0.0)

    trim: MediaTrim = Field(default_factory=MediaTrim)
    crop: MediaCrop = Field(default_factory=MediaCrop)

    #: Logo only.
    logo_placement: LogoPlacement = LogoPlacement.BOTTOM_RIGHT
    logo_width_percent: float = Field(default=12.0, gt=0.0, le=50.0)
    logo_inset_px: int = Field(default=24, ge=0, le=200)
    logo_opacity: float = Field(default=1.0, gt=0.0, le=1.0)

    #: Provenance. Empty for `USER_UPLOAD` by definition — that is the point of
    #: the distinction — and mandatory before a `LICENSED_SOURCE` asset may be
    #: placed in a video.
    creator: str = Field(default="", max_length=200)
    licence: str = Field(default="", max_length=120)
    source_name: str = Field(default="", max_length=120)
    source_url: str = Field(default="", max_length=2000)
    attribution: str = Field(default="", max_length=400)

    #: Which visual units currently show this. Maintained by the API so the
    #: library can say "used in Visual 03" without scanning every unit.
    used_by_unit_ids: list[Id] = Field(default_factory=list, max_length=400)

    #: A sentence for the user when the status needs one — a refusal reason, or
    #: what is happening during ingest.
    detail: str = Field(default="", max_length=400)

    @model_validator(mode="after")
    def _ready_means_usable(self) -> MediaAsset:
        if self.status is MediaStatus.READY and self.object is None:
            raise ValueError("a ready asset must have bytes")
        # Rule 5, restated for this model: unknown rights behave exactly like
        # denied rights. A third-party file with no licence recorded is not
        # "probably fine".
        if (
            self.origin is MediaOrigin.LICENSED_SOURCE
            and self.status is MediaStatus.READY
            and not (self.licence.strip() and self.source_name.strip())
        ):
            raise ValueError("a licensed asset must record its licence and its source")
        return self

    @property
    def is_usable(self) -> bool:
        return self.status is MediaStatus.READY and self.object is not None

    @property
    def is_user_owned(self) -> bool:
        """No licence question, and never replaced without being asked."""
        return self.origin is MediaOrigin.USER_UPLOAD

    @property
    def can_be_a_visual(self) -> bool:
        """A logo rides every scene as an overlay; it is never a shot."""
        return self.kind in {MediaKind.IMAGE, MediaKind.VIDEO, MediaKind.VECTOR}

    @property
    def is_temporal(self) -> bool:
        """Has a duration of its own, and therefore a trim."""
        return self.kind in {MediaKind.VIDEO, MediaKind.AUDIO}

    @property
    def can_be_cropped(self) -> bool:
        """A vector has no pixels to lose, so it scales instead."""
        return self.kind in {MediaKind.IMAGE, MediaKind.VIDEO}

    @property
    def effective_duration_seconds(self) -> Seconds | None:
        """How long this plays after the user's trim."""
        if not self.is_temporal:
            return None
        trimmed = self.trim.duration_seconds
        if trimmed is not None:
            return trimmed
        if self.source_duration_seconds is None:
            return None
        return round(max(0.0, self.source_duration_seconds - self.trim.in_seconds), 3)

    def capabilities(self) -> dict[str, bool]:
        """What the interface may offer for this asset.

        Served rather than inferred client-side. The rules are per kind and they
        are not obvious — "a video can be cropped but an SVG cannot, and neither
        can be used as a logo" is exactly the sort of thing two implementations
        would get subtly different.
        """
        return {
            "visual": self.can_be_a_visual,
            "overlay": self.kind in {MediaKind.LOGO, MediaKind.VECTOR},
            "audio_lane": self.kind is MediaKind.AUDIO,
            "trim": self.is_temporal,
            "crop": self.can_be_cropped,
            "level": self.kind is MediaKind.AUDIO,
            "loop": self.kind is MediaKind.AUDIO,
            "project_mark": self.kind is MediaKind.LOGO,
        }


class MediaLibrary(RootDocument, Timestamped):
    """Every asset in one project, as one stored document.

    One document rather than a row per asset, for the same reason the visual
    units are one document: a project is one thing to load, one thing to delete
    and one thing to retain, and a second storage shape is a second thing for
    `RetentionService` to remember.
    """

    document_name = "media_library"

    organisation_id: Id
    project_id: Id
    assets: list[MediaAsset] = Field(default_factory=list, max_length=500)

    def asset(self, media_asset_id: str) -> MediaAsset | None:
        for item in self.assets:
            if item.media_asset_id == media_asset_id:
                return item
        return None

    def of_kind(self, kind: MediaKind) -> list[MediaAsset]:
        return [item for item in self.assets if item.kind is kind]

    @property
    def project_mark(self) -> MediaAsset | None:
        """The logo, if one has been set. At most one per project."""
        marks = self.of_kind(MediaKind.LOGO)
        return marks[-1] if marks else None

    @model_validator(mode="after")
    def _ids_are_unique(self) -> MediaLibrary:
        identifiers = [item.media_asset_id for item in self.assets]
        if len(set(identifiers)) != len(identifiers):
            raise ValueError("media asset ids must be unique within a project")
        return self


__all__ = [
    "LogoPlacement",
    "MediaAsset",
    "MediaCrop",
    "MediaKind",
    "MediaLibrary",
    "MediaOrigin",
    "MediaStatus",
    "MediaTrim",
]
