"""Voice-to-Video contracts.

Every transformation in the pipeline has a schema, and every schema lives here
(Rule 9). This package is the shared language of the system: services, workers,
the API and eventually the TypeScript frontend all speak it, the last of those
via the JSON Schema files exported from :mod:`vtv.schema_export`.

The package has exactly two dependencies: the Python standard library and
pydantic. It imports nothing from :mod:`vtv.ports`, nothing from any service, and
nothing from any vendor SDK — a rule enforced by
``tests/test_architecture_boundaries.py`` rather than by good intentions.

The pipeline, and the document each step produces::

    Recording      voice captured                     recording.py
        |
    Transcript     what was said, with timings        transcript.py
        |
    Understanding  what it meant                      semantics.py
        |
    SceneGraph     how it becomes a story             scene.py
        |
    VisualPlan     what each scene should look like   visual_plan.py
        |
    Asset          the media that realises it         asset.py
        |
    Timeline       everything, placed in time         timeline.py
        |
    RenderJob      the finished MP4                   render.py

``Project`` (project.py) ties the chain together and tracks its state.
"""

from __future__ import annotations

from vtv.contracts.asset import (
    EXTERNAL_SOURCES,
    FORBIDDEN_SOURCES,
    Asset,
    AssetDimensions,
    AssetKind,
    AssetProvenance,
    AssetSource,
    License,
    Permission,
)
from vtv.contracts.base import (
    CONTRACTS_VERSION,
    TIME_EPSILON,
    Budget,
    Confidence,
    Duration,
    Id,
    IdPrefix,
    Importance,
    ObjectRef,
    RetentionClass,
    RootDocument,
    Seconds,
    TimeSpan,
    Timestamped,
    UsdAmount,
    VTVModel,
    id_prefix_of,
    new_id,
    stable_fingerprint,
    utc_now,
)
from vtv.contracts.consistency import (
    BindingKind,
    BindingSource,
    ContinuityIssue,
    EntityBinding,
    PaletteLock,
    VisualBible,
)
from vtv.contracts.errors import (
    RETRYABLE_CATEGORIES,
    BudgetExceeded,
    DegradationReason,
    DegradationStep,
    ErrorCategory,
    ErrorCode,
    ErrorInfo,
    NotFound,
    PolicyViolation,
    ProviderError,
    ProviderRefused,
    RenderFailed,
    Status,
    TimeoutExceeded,
    ValidationFailed,
    VTVError,
)
from vtv.contracts.generation import (
    GenerationKind,
    GenerationParams,
    GenerationRequest,
    GenerationResult,
    ImageParams,
    SpeechToTextParams,
    TextParams,
    TokenUsage,
    VideoParams,
)
from vtv.contracts.language import (
    LANGUAGES,
    Language,
    LanguagePolicy,
    Script,
    ScriptSupport,
    TranslationRequest,
    TranslationResult,
    detect_script,
    scripts_present,
)
from vtv.contracts.project import (
    STAGE_ORDER,
    PersistenceMode,
    PipelineStage,
    ProcessingConsent,
    Project,
    StageState,
)
from vtv.contracts.recording import (
    MAX_RECORDING_SECONDS,
    MIN_RECORDING_SECONDS,
    AudioFormat,
    AudioProperties,
    CaptureSource,
    Recording,
)
from vtv.contracts.render import (
    RenderJob,
    RenderQuality,
    RenderSettings,
    VideoCodec,
)
from vtv.contracts.scene import (
    MAX_SCENE_SECONDS,
    MIN_SCENE_SECONDS,
    Continuity,
    NarrativeArc,
    Scene,
    SceneGraph,
    ScenePurpose,
    Shot,
    VisualGoal,
)
from vtv.contracts.semantics import (
    NON_VISUAL_INTENTS,
    Entity,
    EntityType,
    ExternalReference,
    Quantity,
    Relation,
    SemanticIntent,
    SemanticUnit,
    Understanding,
)
from vtv.contracts.source import (
    NARRATABLE,
    BlockKind,
    IngestionResult,
    InputKind,
    SourceBlock,
    SourceDocument,
    SourceLocation,
    TableData,
)
from vtv.contracts.style import (
    AspectRatio,
    ColorPalette,
    MotionIntensity,
    StyleProfile,
    VisualStyle,
)
from vtv.contracts.tenancy import (
    ROLE_CAPABILITIES,
    ApiKey,
    AuditAction,
    AuditEvent,
    Capability,
    DataResidency,
    Membership,
    Organisation,
    PlanTier,
    Principal,
    PrincipalKind,
    Role,
    User,
    capabilities_for,
)
from vtv.contracts.timeline import (
    AssetClipSource,
    CaptionCue,
    ClipSource,
    FitPolicy,
    NarrationTrack,
    PlaceholderClipSource,
    ProgrammaticClipSource,
    Timeline,
    Transition,
    TransitionKind,
    VisualClip,
)
from vtv.contracts.transcript import Transcript, TranscriptSegment, TranscriptWord
from vtv.contracts.visual_language import (
    ANIMATION_SPEC_TYPES,
    AnimationSpec,
    BaseSpec,
    CameraMotion,
    ChartKind,
    ChartSeries,
    ChartSpec,
    ComparisonSide,
    ComparisonSpec,
    DataPoint,
    Emphasis,
    MapMarker,
    MapSpec,
    NetworkEdge,
    NetworkNode,
    NetworkSpec,
    TimelineEvent,
    TimelineSpec,
    TypographySpec,
    VisualPrimitive,
)
from vtv.contracts.visual_plan import (
    CompositeLayer,
    CompositeRequirements,
    CostEstimate,
    ExistingAssetRequirements,
    ImageGenerationRequirements,
    LicensedMediaRequirements,
    MediaSearchConstraints,
    ProgrammaticRequirements,
    SceneVisualPlan,
    VideoGenerationRequirements,
    VisualDirective,
    VisualPlan,
    VisualRequirements,
    VisualStrategy,
)

#: Every document that is persisted on its own and therefore has a stable,
#: exported JSON Schema. The schema export, the contract-drift test and the
#: language-model response validation all read from this one list.
ROOT_DOCUMENTS: tuple[type[RootDocument], ...] = (
    Project,
    Recording,
    Transcript,
    Understanding,
    SceneGraph,
    VisualPlan,
    Asset,
    GenerationRequest,
    GenerationResult,
    Timeline,
    RenderJob,
    SourceDocument,
    Organisation,
    User,
    ApiKey,
    AuditEvent,
    VisualBible,
)

__all__ = [
    "ANIMATION_SPEC_TYPES",
    "CONTRACTS_VERSION",
    "EXTERNAL_SOURCES",
    "FORBIDDEN_SOURCES",
    "LANGUAGES",
    "MAX_RECORDING_SECONDS",
    "MAX_SCENE_SECONDS",
    "MIN_RECORDING_SECONDS",
    "MIN_SCENE_SECONDS",
    "NARRATABLE",
    "NON_VISUAL_INTENTS",
    "RETRYABLE_CATEGORIES",
    "ROLE_CAPABILITIES",
    "ROOT_DOCUMENTS",
    "STAGE_ORDER",
    "TIME_EPSILON",
    "AnimationSpec",
    "ApiKey",
    "AspectRatio",
    "Asset",
    "AssetClipSource",
    "AssetDimensions",
    "AssetKind",
    "AssetProvenance",
    "AssetSource",
    "AudioFormat",
    "AudioProperties",
    "AuditAction",
    "AuditEvent",
    "BaseSpec",
    "BindingKind",
    "BindingSource",
    "BlockKind",
    "Budget",
    "BudgetExceeded",
    "CameraMotion",
    "Capability",
    "CaptionCue",
    "CaptureSource",
    "ChartKind",
    "ChartSeries",
    "ChartSpec",
    "ClipSource",
    "ColorPalette",
    "ComparisonSide",
    "ComparisonSpec",
    "CompositeLayer",
    "CompositeRequirements",
    "Confidence",
    "Continuity",
    "ContinuityIssue",
    "CostEstimate",
    "DataPoint",
    "DataResidency",
    "DegradationReason",
    "DegradationStep",
    "Duration",
    "Emphasis",
    "Entity",
    "EntityBinding",
    "EntityType",
    "ErrorCategory",
    "ErrorCode",
    "ErrorInfo",
    "ExistingAssetRequirements",
    "ExternalReference",
    "FitPolicy",
    "GenerationKind",
    "GenerationParams",
    "GenerationRequest",
    "GenerationResult",
    "Id",
    "IdPrefix",
    "ImageGenerationRequirements",
    "ImageParams",
    "Importance",
    "IngestionResult",
    "InputKind",
    "Language",
    "LanguagePolicy",
    "License",
    "LicensedMediaRequirements",
    "MapMarker",
    "MapSpec",
    "MediaSearchConstraints",
    "Membership",
    "MotionIntensity",
    "NarrationTrack",
    "NarrativeArc",
    "NetworkEdge",
    "NetworkNode",
    "NetworkSpec",
    "NotFound",
    "ObjectRef",
    "Organisation",
    "PaletteLock",
    "Permission",
    "PersistenceMode",
    "PipelineStage",
    "PlaceholderClipSource",
    "PlanTier",
    "PolicyViolation",
    "Principal",
    "PrincipalKind",
    "ProcessingConsent",
    "ProgrammaticClipSource",
    "ProgrammaticRequirements",
    "Project",
    "ProviderError",
    "ProviderRefused",
    "Quantity",
    "Recording",
    "Relation",
    "RenderFailed",
    "RenderJob",
    "RenderQuality",
    "RenderSettings",
    "RetentionClass",
    "Role",
    "RootDocument",
    "Scene",
    "SceneGraph",
    "ScenePurpose",
    "SceneVisualPlan",
    "Script",
    "ScriptSupport",
    "Seconds",
    "SemanticIntent",
    "SemanticUnit",
    "Shot",
    "SourceBlock",
    "SourceDocument",
    "SourceLocation",
    "SpeechToTextParams",
    "StageState",
    "Status",
    "StyleProfile",
    "TableData",
    "TextParams",
    "TimeSpan",
    "Timeline",
    "TimelineEvent",
    "TimelineSpec",
    "TimeoutExceeded",
    "Timestamped",
    "TokenUsage",
    "Transcript",
    "TranscriptSegment",
    "TranscriptWord",
    "Transition",
    "TransitionKind",
    "TranslationRequest",
    "TranslationResult",
    "TypographySpec",
    "Understanding",
    "UsdAmount",
    "User",
    "VTVError",
    "VTVModel",
    "ValidationFailed",
    "VideoCodec",
    "VideoGenerationRequirements",
    "VideoParams",
    "VisualBible",
    "VisualClip",
    "VisualDirective",
    "VisualGoal",
    "VisualPlan",
    "VisualPrimitive",
    "VisualRequirements",
    "VisualStrategy",
    "VisualStyle",
    "capabilities_for",
    "detect_script",
    "id_prefix_of",
    "new_id",
    "scripts_present",
    "stable_fingerprint",
    "utc_now",
]
